### ISSUE TITLE
Comments from meeting with Louise

### ISSUE THREAD

**Issue by hkalyn** [CalvinLloyd117/GentleSurvey#1]
Hi Calvin,
I had a nice meeting with Louise today and she gave everything a big thumbs up! There is some tweaking to the question statements slightly to improve clarity, but I will wait on those changes until next week's meetings are complete. Especially since you said those are easy changes that Justin and I can tackle later on if necessary. There were a few (I think?) smaller things that would be nice to change. I will list them below, and please let me know the difficulty level...especially with removing items. If you've taught me one thing about programming, it's that easy things are actually quite difficult! Louise said it is certainly possible for us to try to find another programmer to finish what is too much for you (given the time constraint) so don't hesitate to say 'no'! :) 

Q5a. Remove the "other" box
Q5b. Remove the "Committee Member" option.
Q7. Change this question to ask: If listed, place your supervisor(s) and committee member(s) in the appropriate box.
**Change box titles to "Supervisor(s)" and "Committee Member(s)"
Q8.-Q.14. For the text directly above the yellow box add "at all" or "ever" to the end of the current text. For example: "No technical support ever" or "not comfortable at all".
Q15. Remove the "Not difficult at all" box.

Other notes: We will recruit students one time (not multiple waves) and we will either lock students out of the GENTLE survey after a specified time period to prevent them changing answers too many times, or just extract the data from specific time points and keep it running as one collection. Whichever you advise is easier. Does that make sense?

I hope I got all the major points answered. Please let me know if you have questions! Thanks!

**Comment by hobbitsyfeet** [comment]
I made changes to Q5 through Q18 as stated. https://github.com/CalvinLloyd117/GentleSurvey/commit/9a7ea28cc0b8eb95dc85dd148f51d77205bdac0c

@CalvinLloyd117 I made a testing branch and started a [pull request #2](https://github.com/CalvinLloyd117/GentleSurvey/pull/2)  You can look it over and change things if need be before merging.
