### ISSUE TITLE
Add hyperlink to video introduction

### ISSUE THREAD

**Issue by CalvinLloyd117** [CalvinLloyd117/GentleSurvey#10]
insert a hyperlink in the introduction text with a demo video that explains how to use GENTLE? @hkalyn  will do the demo video part. Easy to add hyperlinks to the html.

However, @hkalyn mentions this is for the folks who will not read the questions. If the participants can't be bothered to read the questions, they definitely won't watch a video. Might not be worth making in my opinion. But the hyperlink is easy.

**Comment by hkalyn** [comment]
That's a good point, Calvin! Maybe making the written instructions more clear is the best option.
