### ISSUE TITLE
Q3. Remove "other" button.

### ISSUE THREAD

**Issue by CalvinLloyd117** [CalvinLloyd117/GentleSurvey#12]
There is no "Other" for these ages. The other options cover all possibilities.

**Comment by hkalyn** [comment]
Sorry, I don't understand this comment. Someone pointed out that we already have all possibilities covered with <20 and 60+ so "other" button is redundant. Does that help?
<img width="1386" alt="Screenshot 2023-07-02 at 2 45 23 PM" src="https://github.com/CalvinLloyd117/GentleSurvey/assets/99207846/3518dd4f-d55f-48fd-9508-3724730eb61c">

**Comment by CalvinLloyd117** [comment]
Option for "Other" has been removed. :)
