### ISSUE TITLE
Q5a. Delete question. 

### ISSUE THREAD

**Issue by CalvinLloyd117** [CalvinLloyd117/GentleSurvey#14]
This will be a difficult one @hkalyn. Unfortunately, I implemented logic for Q5 that takes you either to Q5a or 5b de (or both) depending on the response you gave for 5. This might be one of the more challenging requests, but should be doable.

**Comment by hkalyn** [comment]
Unfortunately, this question format is just too confusing for participants. I'm sorry I didn't realize this sooner, but I think our best option is to remove the drill down (5A and 5C) and create one question from 5B.

**Comment by CalvinLloyd117** [comment]
Drill down mechanic has been removed.
