### ISSUE TITLE
Question re-ordering

### ISSUE THREAD

**Issue by CalvinLloyd117** [CalvinLloyd117/GentleSurvey#17]
Put Q12 and 13 before Q8, 9, 10 and 11.

For this, make sure to reorder the questions (Survey.js), Nav-Links, and Descriptions (Settings.js). Unfortunately, there are a few places these need to be re-ordered. Just make sure to test and ensure the question appear in the order you want.

**Comment by hkalyn** [comment]
I am almost done writing the questions. I will post the new text early this week.

**Comment by hkalyn** [comment]
Here is a Word doc with the text changes. Please let me know if you have any suggestions to make the instructions more clear.
[notes from lab meeting_June2023.docx](https://github.com/CalvinLloyd117/GentleSurvey/files/11940813/notes.from.lab.meeting_June2023.docx)

**Comment by CalvinLloyd117** [comment]
Question order now matches the most up-to-date document. Thanks @hobbitsyfeet. If I might add, the question wording is significantly easier to follow now. Much better descriptions @hkalyn!
