### ISSUE TITLE
Q16 Issues with the Green Dot

### ISSUE THREAD

**Issue by CalvinLloyd117** [CalvinLloyd117/GentleSurvey#18]
People found the green dot annoying or distracting. However, Sam mentioned (which I either didn't realize or forgot) that the green dot can be used to unselect your current option. Would it just be possible to move the green dot to the top left corner of the screen and rename it something like "cancel current selection".

@hkalyn This functionality was a part of the base Gentle, and involves some code in Graph.js, which is quite temperamental. It should be possible to remove the dot, but I don't know how the rest of the nodes will react, since the green dot is the source of gravity for the nodes. Making this modification is a risk/reward type change, and might not be worth compromising the integrity of the code to change. 

It may be possible to hide it with visibility: hidden; in css, but I'm not certain.

**Comment by hkalyn** [comment]
This is good to know. I don't want to mess around with the functionality. I think it may be better to clarify in the instructions that the green dot allows you to clear your current selection and it does not need ties made to it. Can we replace the text "me" with something like "clear selection"? Suggestions?

**Comment by CalvinLloyd117** [comment]
I have removed the Green "You" node, and pulled its onClick functionality into a separate button for deselecting the current node.
