### ISSUE TITLE
Button questions have black nodes

### ISSUE THREAD

**Issue by hkalyn** [CalvinLloyd117/GentleSurvey#4]
We will need to change the node colour to make the names visible. The functioning of the button works for me but it started at the second option (blue) not orange. I had to cycle through all the options to get back to orange. Not sure if that really matters? Also, my account still has 25 alters. If I started from the beginning will I only need to list 20 alters now? Thanks!
<img width="1253" alt="Screenshot 2023-05-26 at 5 12 27 PM" src="https://github.com/CalvinLloyd117/GentleSurvey/assets/99207846/66787bdf-13fd-4168-8f74-1e92c73cc56c">
<img width="1251" alt="Screenshot 2023-05-26 at 5 13 20 PM" src="https://github.com/CalvinLloyd117/GentleSurvey/assets/99207846/474379a5-6877-4040-89e3-6033d078f96a">
<img width="1236" alt="Screenshot 2023-05-26 at 5 13 59 PM" src="https://github.com/CalvinLloyd117/GentleSurvey/assets/99207846/e1a68eab-4542-47f1-8b00-4e39d9b1c625">
<img width="1226" alt="Screenshot 2023-05-26 at 5 14 51 PM" src="https://github.com/CalvinLloyd117/GentleSurvey/assets/99207846/0d6f1694-335e-4896-85ba-ac70b38eb0ff">

**Comment by CalvinLloyd117** [comment]
Indeed. I messaged you about this. Its related to an inconsistent database. The issue wont be there on future accounts, only those made prior to the update.
